import type { Metadata } from "next";
import React, { useEffect } from 'react';

declare global {
  interface Window {
    _mtm?: Array<Record<string, unknown>>;
  }
}
import { Roboto } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import "./globals.css";

const inter = Roboto({
  subsets: ["latin"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Universal Perk Custom AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    const _mtm = window._mtm = window?._mtm || [];
    _mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
    const d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; 
    g.src='https://cdn.matomo.cloud/universalperk.matomo.cloud/container_ajVHcFZt.js'; 
    if (s.parentNode) {
      s.parentNode.insertBefore(g, s);
    } else {
      d.appendChild(g);
    }
   }, [])
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
